name: Get Branch Name

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get short SHA
      run: |
         echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" >> $env:GITHUB_ENV
         echo "TAG_NAME=${{ github.ref_name }}-$("${{ github.sha }}".SubString(0, 8))" >> $env:GITHUB_ENV

    - name: Print short SHA
      run: echo "Short SHA is ${{ env.SHORT_SHA }}"

    - name: Print short TAG
      run: echo "Short TAG is ${{ env.TAG_NAME }}"


    - name: Display branch name
      run: |
        echo "Branch name is ${{ github.ref_name }}"
        echo "Branch name is ${{ github.sha }}"

