name: Get Branch Name

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Display branch name
      run: |
        echo "Branch name is ${{ github.ref_name }}"
        echo "Branch name is ${{ github.sha::10 }}"

